version: '3.3'

volumes:
  database:
  static:
  media:

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - ../.env

  backend:
    build: ../backend/
    depends_on:
      - db
    env_file:
      - ../.env
    volumes:
      - static:/app/static/
      - media:/app/media/

  frontend:
    build: ../frontend/
    depends_on:
      - backend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    depends_on:
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/
    entrypoint: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
      container_name: service_certbot
      image: certbot/certbot
      volumes:
          - ./data/certbot/conf:/etc/letsencrypt
          - ./data/certbot/www:/var/www/certbot
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"