version: '3.8'

volumes:
  static:
  media:

services:
  backend:
    build: ../backend/
    depends_on:
      - db
    env_file:
      - ../.env
    volumes:
      - static:/app/static/
      - media:/app/media/

  frontend:
    build: ../frontend/
    depends_on:
      - backend
    volumes:
      - ../frontend/:/app/result_build/
